sets.geomancy = {
    main={ name="Solstice", augments={'Mag. Acc.+20','Pet: Damage taken -4%','"Fast Cast"+5',}},
    sub="Culminus",
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    head="Azimuth Hood",
    body={ name="Bagua Tunic", augments={'Enhances "Bolster" effect',}},
    hands="Geomancy Mitaines",
    legs={ name="Bagua Pants", augments={'Enhances "Mending Halation" effect',}},
    feet="Azimuth Gaiters",
    neck={ name="Bagua Charm", augments={'Path: A',}},
    waist="Eschan Stone",
    left_ear="Infused Earring",
    right_ear="Loquac. Earring",
    left_ring="Renaye Ring",
    right_ring="Stikini Ring",
    back={ name="Lifestream Cape", augments={'Geomancy Skill +10','Indi. eff. dur. +15','Pet: Damage taken -1%','Damage taken-3%',}},
}

sets.precast.FC = {
    main={ name="Solstice", augments={'Mag. Acc.+20','Pet: Damage taken -4%','"Fast Cast"+5',}},
    sub="Culminus",
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    head="Befouled Crown",
    body="Azimuth Coat",
    hands="Geomancy Mitaines",
    legs="Geomancy Pants",
    feet="Regal Pumps",
    neck="Loricate Torque",
    waist="Eschan Stone",
    left_ear="Infused Earring",
    right_ear="Loquac. Earring",
    left_ring="Gelatinous Ring +1",
    right_ring="Fortified Ring",
    back={ name="Nantosuelta's Cape", augments={'"Fast Cast"+10',}}
}

sets.idle['pet'] = {
    main={ name="Solstice", augments={'Mag. Acc.+20','Pet: Damage taken -4%','"Fast Cast"+5',}},
    sub="Culminus",
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    head="Azimuth Hood",
    body="Azimuth Coat",
    hands="Geomancy Mitaines",
    legs="Psycloth Lappas",
    feet={ name="Bagua Sandals", augments={'Enhances "Radial Arcana" effect',}},
    neck={ name="Bagua Charm", augments={'Path: A',}},
    waist="Isa Belt",
    left_ear="Infused Earring",
    right_ear="Loquac. Earring",
    left_ring="Renaye Ring",
    right_ring="Fortified Ring",
    back={ name="Lifestream Cape", augments={'Geomancy Skill +10','Indi. eff. dur. +15','Pet: Damage taken -1%','Damage taken-3%',}},
}

sets.idle={
    main={ name="Solstice", augments={'Mag. Acc.+20','Pet: Damage taken -4%','"Fast Cast"+5',}},
    sub="Culminus",
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    head="Befouled Crown",
    body="Azimuth Coat",
    hands={ name="Bagua Mitaines", augments={'Enhances "Curative Recantation" effect',}},
    legs="Assiduity Pants",
    feet="Geomancy Sandals",
    neck="Sanctity Necklace",
    waist="Eschan Stone",
    left_ear="Infused Earring",
    right_ear="Loquac. Earring",
    left_ring="Renaye Ring",
    right_ring="Fortified Ring",
    back={ name="Nantosuelta's Cape", augments={'"Fast Cast"+10',}},
}